/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/companies/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all companies
     * @description Retrieve a list of all companies with their emissions, economic data, industry classification, goals, and initiatives
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              wikidataId: string
              name: string
              description: string | null
              reportingPeriods: {
                /** Format: date-time */
                startDate: string
                /** Format: date-time */
                endDate: string
                reportURL: string | null
                emissions: {
                  calculatedTotalEmissions: number
                  scope1: {
                    total: number
                    unit: string
                    metadata: {
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                  scope2: {
                    mb: number | null
                    lb: number | null
                    unknown: number | null
                    unit: string
                    calculatedTotalEmissions: number
                    metadata: {
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                  scope3: {
                    calculatedTotalEmissions: number
                    metadata: {
                      verifiedBy: {
                        name: string
                      } | null
                    }
                    statedTotalEmissions: {
                      total: number
                      unit: string
                      metadata: {
                        verifiedBy: {
                          name: string
                        } | null
                      }
                    } | null
                    categories: {
                      category: number
                      total: number
                      unit: string
                      metadata: {
                        verifiedBy: {
                          name: string
                        } | null
                      }
                    }[]
                  } | null
                  scope1And2: {
                    total: number
                    unit: string
                    metadata: {
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                  statedTotalEmissions: {
                    total: number
                    unit: string
                    metadata: {
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                } | null
                economy: {
                  employees: {
                    value: number | null
                    unit: string | null
                    metadata: {
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                  turnover: {
                    value: number | null
                    currency: string | null
                    metadata: {
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                } | null
              }[]
              industry: {
                industryGics: {
                  sectorCode: string
                  groupCode: string
                  industryCode: string
                  subIndustryCode: string
                }
                metadata: {
                  verifiedBy: {
                    name: string
                  } | null
                }
              } | null
            }[]
          }
        }
      }
    }
    put?: never
    /**
     * Create or update a company
     * @description Creates a new company or updates an existing one based on wikidataId
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            wikidataId: string
            name: string
            description?: string
            /** Format: uri */
            url?: string
            internalComment?: string
            tags?: string[]
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              ok: boolean
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/{wikidataId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get detailed company
     * @description Retrieve a company with its emissions, economic data, industry classification, goals, and initiatives
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          wikidataId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              wikidataId: string
              name: string
              description: string | null
              reportingPeriods: {
                id: string
                /** Format: date-time */
                startDate: string
                /** Format: date-time */
                endDate: string
                reportURL: string | null
                emissions: {
                  id: string
                  scope1: {
                    id: string
                    total: number
                    unit: string
                    metadata: {
                      id: string
                      comment: string | null
                      source: string | null
                      /** Format: date-time */
                      updatedAt: string
                      user: {
                        name: string
                      }
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                  scope2: {
                    id: string
                    mb: number | null
                    lb: number | null
                    unknown: number | null
                    unit: string
                    metadata: {
                      id: string
                      comment: string | null
                      source: string | null
                      /** Format: date-time */
                      updatedAt: string
                      user: {
                        name: string
                      }
                      verifiedBy: {
                        name: string
                      } | null
                    }
                    calculatedTotalEmissions: number
                  } | null
                  scope3: {
                    id: string
                    categories: {
                      id: string
                      category: number
                      total: number
                      unit: string
                      metadata: {
                        id: string
                        comment: string | null
                        source: string | null
                        /** Format: date-time */
                        updatedAt: string
                        user: {
                          name: string
                        }
                        verifiedBy: {
                          name: string
                        } | null
                      }
                    }[]
                    statedTotalEmissions: {
                      id: string
                      total: number
                      unit: string
                      metadata: {
                        id: string
                        comment: string | null
                        source: string | null
                        /** Format: date-time */
                        updatedAt: string
                        user: {
                          name: string
                        }
                        verifiedBy: {
                          name: string
                        } | null
                      }
                    } | null
                    calculatedTotalEmissions: number
                    metadata: {
                      id: string
                      comment: string | null
                      source: string | null
                      /** Format: date-time */
                      updatedAt: string
                      user: {
                        name: string
                      }
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                  scope1And2: {
                    id: string
                    total: number
                    unit: string
                    metadata: {
                      id: string
                      comment: string | null
                      source: string | null
                      /** Format: date-time */
                      updatedAt: string
                      user: {
                        name: string
                      }
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                  biogenicEmissions: {
                    id: string
                    total: number
                    unit: string
                    metadata: {
                      id: string
                      comment: string | null
                      source: string | null
                      /** Format: date-time */
                      updatedAt: string
                      user: {
                        name: string
                      }
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                  statedTotalEmissions: {
                    id: string
                    total: number
                    unit: string
                    metadata: {
                      id: string
                      comment: string | null
                      source: string | null
                      /** Format: date-time */
                      updatedAt: string
                      user: {
                        name: string
                      }
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                  calculatedTotalEmissions: number
                } | null
                economy: {
                  id: string
                  turnover: {
                    id: string
                    value: number | null
                    currency: string | null
                    metadata: {
                      id: string
                      comment: string | null
                      source: string | null
                      /** Format: date-time */
                      updatedAt: string
                      user: {
                        name: string
                      }
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                  employees: {
                    id: string
                    value: number | null
                    unit: string | null
                    metadata: {
                      id: string
                      comment: string | null
                      source: string | null
                      /** Format: date-time */
                      updatedAt: string
                      user: {
                        name: string
                      }
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  } | null
                } | null
              }[]
              industry: {
                id: string
                industryGics: {
                  sectorCode: string
                  groupCode: string
                  industryCode: string
                  subIndustryCode: string
                  sv: {
                    sectorName: string
                    groupName: string
                    industryName: string
                    subIndustryName: string
                    subIndustryDescription: string
                  }
                  en: {
                    sectorName: string
                    groupName: string
                    industryName: string
                    subIndustryName: string
                    subIndustryDescription: string
                  }
                }
                metadata: {
                  id: string
                  comment: string | null
                  source: string | null
                  /** Format: date-time */
                  updatedAt: string
                  user: {
                    name: string
                  }
                  verifiedBy: {
                    name: string
                  } | null
                }
              } | null
              goals:
                | {
                    id: string
                    description: string
                    year: string | null
                    baseYear: string | null
                    target: number | null
                    metadata: {
                      id: string
                      comment: string | null
                      source: string | null
                      /** Format: date-time */
                      updatedAt: string
                      user: {
                        name: string
                      }
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  }[]
                | null
              initiatives:
                | {
                    id: string
                    title: string
                    description: string | null
                    year: string | null
                    scope: string | null
                    metadata: {
                      id: string
                      comment: string | null
                      source: string | null
                      /** Format: date-time */
                      updatedAt: string
                      user: {
                        name: string
                      }
                      verifiedBy: {
                        name: string
                      } | null
                    }
                  }[]
                | null
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    put?: never
    post?: never
    /**
     * Delete company
     * @description Delete a company by Wikidata ID
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          wikidataId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/municipalities/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all municipalities
     * @description Retrieve a list of all municipalities with data about their emissions, carbon budget, climate plans, bike infrastructure, procurements and much more.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              name: string
              region: string
              emissions: {
                [key: string]: number
              }
              budget: number
              emissionBudget: {
                [key: string]: number
              }
              approximatedHistoricalEmission: {
                [key: string]: number
              }
              totalApproximatedHistoricalEmission: number
              trend: {
                [key: string]: number
              }
              trendEmission: number
              historicalEmissionChangePercent: number
              neededEmissionChangePercent: number
              hitNetZero: string
              budgetRunsOut: string
              electricCarChangePercent: number
              electricCarChangeYearly: {
                [key: string]: number
              }
              climatePlanLink: string
              climatePlanYear: 'Saknar plan' | number
              climatePlanComment: string
              bicycleMetrePerCapita: number
              totalConsumptionEmission: number
              electricVehiclePerChargePoints: number
              procurementScore: string
              procurementLink: string
            }[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/municipalities/{name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get one municipality
     * @description Retrieve a one municipality with data about their emissions, carbon budget, climate plans, bike infrastructure, procurements and much more.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          name: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              name: string
              region: string
              emissions: {
                [key: string]: number
              }
              budget: number
              emissionBudget: {
                [key: string]: number
              }
              approximatedHistoricalEmission: {
                [key: string]: number
              }
              totalApproximatedHistoricalEmission: number
              trend: {
                [key: string]: number
              }
              trendEmission: number
              historicalEmissionChangePercent: number
              neededEmissionChangePercent: number
              hitNetZero: string
              budgetRunsOut: string
              electricCarChangePercent: number
              electricCarChangeYearly: {
                [key: string]: number
              }
              climatePlanLink: string
              climatePlanYear: 'Saknar plan' | number
              climatePlanComment: string
              bicycleMetrePerCapita: number
              totalConsumptionEmission: number
              electricVehiclePerChargePoints: number
              procurementScore: string
              procurementLink: string
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/{wikidataId}/industry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Update company industry
     * @description Update or create industry classification for a company based on the GICS standard
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          wikidataId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            industry: {
              subIndustryCode: string
            }
            metadata?: {
              source?: string
              comment?: string
            }
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              ok: boolean
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    /**
     * Delete industry
     * @description Delete a company industry
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/{wikidataId}/reporting-periods': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create or update reporting periods
     * @description Create or update reporting periods for a specific company. This is used to update emissions and economy data.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          wikidataId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            reportingPeriods: {
              /** Format: date-time */
              startDate: string
              /** Format: date-time */
              endDate: string
              reportURL?: string
              emissions?: {
                scope1?: {
                  total: number
                }
                scope2?: {
                  /** @description Market-based scope 2 emissions */
                  mb?: number
                  /** @description Location-based scope 2 emissions */
                  lb?: number
                  /** @description Unspecified Scope 2 emissions */
                  unknown?: number
                }
                scope3?: {
                  categories?: {
                    category: number
                    total: number
                  }[]
                  statedTotalEmissions?: {
                    total: number
                  }
                }
                biogenic?: {
                  total: number
                }
                statedTotalEmissions?: {
                  total: number
                }
                scope1And2?: {
                  total: number
                }
              }
              economy?: {
                turnover?: {
                  value?: number
                  currency?: string
                }
                employees?: {
                  value?: number
                  unit?: string
                }
              }
            }[]
            metadata?: {
              source?: string
              comment?: string
            }
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              ok: boolean
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/{wikidataId}/goals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create company goals
     * @description Create new goals for a company
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          wikidataId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            goals: {
              description: string
              year?: string
              target?: number
              baseYear?: string
            }[]
            metadata?: {
              source?: string
              comment?: string
            }
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              ok: boolean
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/{wikidataId}/goals/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update company goal
     * @description Update a goal for a company
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            goal: {
              description: string
              year?: string
              target?: number
              baseYear?: string
            }
            metadata?: {
              source?: string
              comment?: string
            }
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              ok: boolean
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    trace?: never
  }
  '/companies/{wikidataId}/initiatives': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create company initiatives
     * @description Create new initiatives for a company
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          wikidataId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            initiatives: {
              title: string
              description?: string
              year?: string
              scope?: string
            }[]
            metadata?: {
              source?: string
              comment?: string
            }
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              ok: boolean
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/{wikidataId}/initiatives/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update a company initiative
     * @description Update an existing initiative for a company
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            initiative: {
              title: string
              description?: string
              year?: string
              scope?: string
            }
            metadata?: {
              source?: string
              comment?: string
            }
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              ok: boolean
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    trace?: never
  }
  '/companies/goals/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete a goal
     * @description Delete a goal by id
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/initiatives/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete an initiative
     * @description Delete an initiative by id
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/reporting-period/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete a reporting period
     * @description Delete a reporting period by id
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/stated-total-emissions/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete stated total emissions
     * @description Delete stated total emissions by id
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/biogenic-emissions/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete biogenic emissions
     * @description Delete biogenic emissions by id
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/scope1/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Scope1
     * @description Delete the Scope1 emissions by id
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/scope1and2/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete scope1and2
     * @description Delete a scope1and2 by id
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/scope2/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete scope2
     * @description Delete a scope2 by id
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/scope3/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete scope3
     * @description Delete a scope3 by id
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/companies/scope3-category/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete a scope3 category
     * @description Delete a scope3 category by id
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              code: string
              message?: string
              details?: unknown
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
