apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        location /api/ {
            proxy_pass http://garbo.garbo.svc.cluster.local/api/; # Production service name
        }
    }
